name: Update IPTV

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python merge.py

      - name: Commit Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto update IPTV
